# See also https://alacritty.org/config-alacritty.html for how to config this

[colors]
cursor = { text = "CellBackground", cursor = "#A1C6EA" }
selection = { text = "CellBackground", cursor = "#A1C6EA" }

# Color theme (Tokyo Night Storm variant)
# Original Source https//github.com/zatchheems/tokyo-night-alacritty-theme
# Source https://github.com/alacritty/alacritty-theme

[colors.primary]
background = '#24283b'
foreground = '#a9b1d6'

[colors.normal]
black   = '#32344a'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#ad8ee6'
cyan    = '#449dab'
white   = '#9699a8'

[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'
green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#7da6ff'
magenta = '#bb9af7'
cyan    = '#0db9d7'
white   = '#acb0d0'

[cursor]
style = { shape = "Beam", blinking = "Off" }
thickness = 0.3

[font]
size = 14

[hints]

[keyboard]

[mouse]

[scrolling]
history = 30000

[selection]
save_to_clipboard = true

[terminal]

[window]
padding.x = 10
padding.y = 0
option_as_alt = "Both" # Mac only; Need this so I can use ALT as Meta in Emacs