BASE="$HOME/dotfiles/shell/zsh"
FIRST=source_first

# these get sourced first
for file in "$BASE/$FIRST"/*.zsh; do
  source "$file"
done

# these get sourced last
for file in "$BASE"/*.zsh; do
  source "$file"
done

# bun completions
[ -s "/home/apmiller/.bun/_bun" ] && source "/home/apmiller/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
