BASE="$HOME/dotfiles/shell/zsh"
FIRST=source_first

# these get last first
for file in "$BASE/$FIRST"/*.zsh; do
  source "$file"
done

# these get sources last
for file in "$BASE"/*.zsh; do
  source "$file"
done
