BASE="$HOME/dotfiles/shell/zsh"
FIRST=source_first

# these get sourced first
for file in "$BASE/$FIRST"/*.zsh; do
  source "$file"
done

# these get sourced last
for file in "$BASE"/*.zsh; do
  source "$file"
done

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

